// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHit_HuZxGP5HPzMd55ZXjHrL0ued-83w',
    appId: '1:311503372371:web:963f0958dc87a8b5b846a6',
    messagingSenderId: '311503372371',
    projectId: 'prmfinalproject-6ba7a',
    authDomain: 'prmfinalproject-6ba7a.firebaseapp.com',
    storageBucket: 'prmfinalproject-6ba7a.firebasestorage.app',
    measurementId: 'G-GT1TTQ9K99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADvbbHydvki41Yd62mKa7FuxROK5_ehWU',
    appId: '1:311503372371:android:398fdbbc03a96d06b846a6',
    messagingSenderId: '311503372371',
    projectId: 'prmfinalproject-6ba7a',
    storageBucket: 'prmfinalproject-6ba7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChFjr35iGCMV36AkuxSMHUZkGsppL3Smc',
    appId: '1:311503372371:ios:510dcba8227f6014b846a6',
    messagingSenderId: '311503372371',
    projectId: 'prmfinalproject-6ba7a',
    storageBucket: 'prmfinalproject-6ba7a.firebasestorage.app',
    iosBundleId: 'com.example.prmProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChFjr35iGCMV36AkuxSMHUZkGsppL3Smc',
    appId: '1:311503372371:ios:510dcba8227f6014b846a6',
    messagingSenderId: '311503372371',
    projectId: 'prmfinalproject-6ba7a',
    storageBucket: 'prmfinalproject-6ba7a.firebasestorage.app',
    iosBundleId: 'com.example.prmProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHit_HuZxGP5HPzMd55ZXjHrL0ued-83w',
    appId: '1:311503372371:web:3f8d3e40f88a03fab846a6',
    messagingSenderId: '311503372371',
    projectId: 'prmfinalproject-6ba7a',
    authDomain: 'prmfinalproject-6ba7a.firebaseapp.com',
    storageBucket: 'prmfinalproject-6ba7a.firebasestorage.app',
    measurementId: 'G-261C01SVX9',
  );
}
